version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:1919"
    environment:
      - NODE_ENV
      - DATABASE_URL
      - SUPABASE_URL
      - SUPABASE_KEY
      - SUPABASE_JWT_SECRET
      - JWT_SECRET
      - JWT_EXPIRES_IN
      - FRONTEND_URL
      - PORT
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:1919/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
